---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
  namespace: nginx-system
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Nginx</title>
    </head>
    <body>
      <h1> GITOPS!!! </h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-html
        configMap:
          name: nginx-index-html-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-system
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80